@extends('frontend.master')
@section('title', 'Shop Bán tài khoản game CF chuyên nghiệp uy tín, giá rẻ tất cả các loại acc hàng đầu VN ShopGame88.com')
@section('description', 'Giao dịch nhanh gọn lẹ, Bán acc Đột kích ,CF, giá rẻ mà còn cực kỳ uy tín ShopGame88.com')
@section('keywords', 'shop Đột kích, mua acc CF, mua nick CF, bán acc lq, shop lq, acc lien quan gia re, ShopGame88.com')
@section('main')
@section('content_seo', '
    Chào mừng bạn đến với Shop Đột kích ("Shop Đột kích," "chúng tôi" hoặc "của chúng tôi"). Shop Đột kích cung cấp cách chia sẻ phương tiện nhanh chóng, tuyệt vời và vui nhộn thông qua nền tảng chia sẻ nội dung của chúng tôi. Chỉ cần chụp ảnh nhanh, chọn bộ lọc để thay đổi hình thức, thêm bình luận (nếu bạn thích) và chia sẻ! Chính sách quyền riêng tư của chúng tôi giải thích cách chúng tôi và một số công ty mà chúng tôi hợp tác sẽ thu thập, sử dụng, chia sẻ và bảo vệ thông tin liên quan đến các dịch vụ dành cho thiết bị di động, trang web và bất kỳ phần mềm nào được cung cấp về hoặc liên quan đến các dịch vụ của Shop Đột kích (gọi chung là "Dịch vụ") và lựa chọn của bạn đối với việc thu thập và sử dụng thông tin của bạn. Bằng cách sử dụng Dịch vụ của chúng tôi, bạn hiểu và đồng ý rằng chúng tôi sẽ cung cấp cho bạn một nền tảng để đăng nội dung, bao gồm ảnh, bình luận và tài liệu khác ("Nội dung của người dùng") lên Dịch vụ và chia sẻ Nội dung của người dùng một cách công khai. Điều này nghĩa là những Người dùng khác có thể tìm kiếm, xem, sử dụng hoặc chia sẻ mọi Nội dung của người dùng mà bạn đăng công khai thông qua Dịch vụ, thống nhất với các điều khoản và điều kiện của Chính sách quyền riêng tư này cũng như Điều khoản sử dụng của chúng tôi . Chính sách của chúng tôi áp dụng với tất cả khách truy cập, người dùng và những người khác truy cập vào Dịch vụ ("Người dùng").
    Thông tin bạn cung cấp trực tiếp cho chúng tôi.
    Tên người dùng, mật khẩu và địa chỉ email của bạn khi bạn đăng ký tài khoản Shop Đột kích.
    Thông tin tiểu sử bạn cung cấp cho hồ sơ người dùng (ví dụ: họ và tên, ảnh, số điện thoại). Thông tin này cho phép chúng tôi giúp bạn hoặc những người khác "được tìm thấy" trên Shop Đột kích.
    Nội dung của người dùng (ví dụ: ảnh, bình luận và các tài liệu khác) bạn đăng lên Dịch vụ.
    Liên lạc giữa bạn và Shop Đột kích. Ví dụ: chúng tôi có thể gửi cho bạn email liên quan đến Dịch vụ (ví dụ: xác minh tài khoản, thay đổi/cập nhật các tính năng của Dịch vụ, thông báo kỹ thuật và bảo mật). Lưu ý rằng bạn không thể bỏ nhận email liên quan đến Dịch vụ.
    Chúng tôi sử dụng các công cụ phân tích của bên thứ ba để giúp chúng tôi đánh giá xu hướng sử dụng và lưu lượng truy cập Dịch vụ. Những công cụ này sẽ thu thập thông tin được thiết bị của bạn hoặc Dịch vụ của chúng tôi gửi, bao gồm trang web bạn truy cập, tiện ích mở rộng và những thông tin khác hỗ trợ chúng tôi cải thiện Dịch vụ.
    Chúng tôi sẽ thu thập và sử dụng thông tin phân tích này cùng thông tin phân tích từ những Người dùng khác để không thể sử dụng một cách hợp lý nhằm xác định bất kỳ Người dùng riêng cụ thể nào.
    Cookie và các công nghệ tương tự.
    Khi bạn truy cập Dịch vụ, chúng tôi có thể sử dụng cookie và các công nghệ tương tự như pixel, tập tin chỉ báo và bộ nhớ cục bộ để thu thập thông tin về cách bạn sử dụng Shop Đột kích cũng như cung cấp cho bạn các tính năng.
    Chúng tôi có thể yêu cầu các nhà quảng cáo hoặc đối tác khác phân phối quảng cáo hoặc dịch vụ đến các thiết bị của bạn. Họ có thể sử dụng cookie hoặc các công nghệ tương tự được chúng tôi hoặc bên thứ ba đưa vào.
    Thông tin tệp nhật ký được trình duyệt của bạn tự động báo cáo mỗi khi bạn đưa ra yêu cầu truy cập (ví dụ: truy cập) trang web hoặc ứng dụng. Thông tin này cũng có thể được cung cấp khi nội dung của trang web hoặc ứng dụng được tải xuống trình duyệt hoặc thiết bị của bạn.
    Khi bạn sử dụng Dịch vụ của chúng tôi, các máy chủ của chúng tôi sẽ tự động ghi lại thông tin tệp nhật ký, bao gồm yêu cầu web, địa chỉ Giao thức Internet ("IP"), loại trình duyệt, URL và trang thoát/giới thiệu, số lần nhấp và cách bạn tương tác với liên kết trên Dịch vụ, tên miền, trang đích, trang đã xem và thông tin tương tự khác. Chúng tôi cũng có thể thu thập thông tin tương tự từ email được gửi đến những Người dùng của mình giúp chúng tôi theo dõi email nào đã được mở cũng như liên kết nào đã được người nhận nhấp vào. Thông tin này cho phép báo cáo chính xác hơn và cải thiện Dịch vụ.
    Khi bạn sử dụng thiết bị di động như máy tính bảng hoặc điện thoại để truy cập Dịch vụ của chúng tôi, chúng tôi có thể truy cập, thu thập, giám sát, lưu trữ trên thiết bị của bạn và/hoặc lưu trữ từ xa một hoặc nhiều "số nhận dạng thiết bị". Số nhận dạng thiết bị là những tệp dữ liệu nhỏ hoặc cấu trúc dữ liệu tương tự trên hoặc được liên kết với thiết bị di động của bạn. Số nhận dạng thiết bị nhận dạng duy nhất thiết bị di động của bạn. Số nhận dạng thiết bị có thể là dữ liệu được lưu trữ liên quan đến phần cứng thiết bị, dữ liệu được lưu trữ liên quan đến hệ điều hành hoặc phần mềm khác của thiết bị hoặc dữ liệu được Shop Đột kích gửi đến thiết bị của bạn.
')
@section('title_h2_1', 'Shop Đột kích hoặc những Người dùng khác có thể thực hiện cuộc thi, ưu đãi đặc biệt hoặc sự kiện hay hoạt động ("Sự kiện") khác trên Dịch vụ. Nếu bạn không tham gia vào Sự kiện, đừng sử dụng Siêu dữ liệu cụ thể (tức là hashtag hoặc thẻ địa lý) được liên kết với Sự kiện đó.')
@section('title_h2_2', 'Nếu bạn xóa thông tin mình đã đăng lên Dịch vụ, các bản sao vẫn có thể xem được trong các trang được lưu vào bộ nhớ đệm và được lưu trữ của Dịch vụ hoặc nếu những Người dùng khác hoặc bên thứ ba đang sử dụng API Shop Đột kích đã sao chép hoặc lưu thông tin đó.')
@section('title_h3_1', 'Shop Đột kích, Chi nhánh hoặc Nhà cung cấp dịch vụ của mình có thể truyền thông tin mà chúng tôi thu thập về bạn, bao gồm thông tin cá nhân qua biên giới và từ quốc gia hoặc khu vực pháp lý của bạn đến quốc gia hoặc khu vực khác trên toàn thế giới. Nếu bạn đang sống tại Đột kích châu Âu hoặc khu vực khác có luật điều chỉnh việc thu thập và sử dụng dữ liệu có thể khác với luật của Hoa Kỳ, xin lưu ý rằng chúng tôi có thể truyền thông tin, bao gồm thông tin cá nhân, tới quốc gia và khu vực pháp lý không có luật bảo vệ dữ liệu giống như tại khu vực pháp lý của bạn.')
@section('title_h3_2', 'Thông tin tài khoản và thiết lập trang cá nhân/quyền riêng tư của bạn: Cập nhật tài khoản bất kỳ lúc nào bằng cách đăng nhập và thay đổi cài đặt trang cá nhân của bạn.')
@section('title_h3_3', 'Bán Acc Random các loại, Đột kích, Đột kích, Đột kích hàn quốc ,...')
@include('frontend.account.account-home')
@stop

